#include <catch2/catch_all.hpp>

TEST_CASE("failing test") {
  FAIL("failed");
}
